/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as Signed_inRouteImport } from './routes/_signed_in'
import { Route as Signed_inIndexRouteImport } from './routes/_signed_in/index'
import { Route as Signed_inPluginsLobbyRouteImport } from './routes/_signed_in/plugins/lobby'
import { Route as Signed_inPluginsMainRouteImport } from './routes/_signed_in/plugins/main'
import { Route as Signed_inPluginsResRouteImport } from './routes/_signed_in/plugins/res'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AuthSignInIndexRouteImport } from './routes/auth/sign-in/index'
import { Route as Signed_inRailwayGroupIndexRouteImport } from './routes/_signed_in/railway/group/index'
import { Route as Signed_inRailwayGroupIdRouteImport } from './routes/_signed_in/railway/group/$id'
import { Route as Signed_inRailwayRailwayIndexRouteImport } from './routes/_signed_in/railway/railway/index'
import { Route as Signed_inRailwayStationIndexRouteImport } from './routes/_signed_in/railway/station/index'

const Signed_inRoute = Signed_inRouteImport.update({
  id: '/_signed_in',
  getParentRoute: () => rootRouteImport,
} as any)
const Signed_inIndexRoute = Signed_inIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => Signed_inRoute,
} as any)
const Signed_inPluginsLobbyRoute = Signed_inPluginsLobbyRouteImport.update({
  id: '/plugins/lobby',
  path: '/plugins/lobby',
  getParentRoute: () => Signed_inRoute,
} as any)
const Signed_inPluginsMainRoute = Signed_inPluginsMainRouteImport.update({
  id: '/plugins/main',
  path: '/plugins/main',
  getParentRoute: () => Signed_inRoute,
} as any)
const Signed_inPluginsResRoute = Signed_inPluginsResRouteImport.update({
  id: '/plugins/res',
  path: '/plugins/res',
  getParentRoute: () => Signed_inRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignInIndexRoute = AuthSignInIndexRouteImport.update({
  id: '/auth/sign-in/',
  path: '/auth/sign-in/',
  getParentRoute: () => rootRouteImport,
} as any)
const Signed_inRailwayGroupIndexRoute =
  Signed_inRailwayGroupIndexRouteImport.update({
    id: '/railway/group/',
    path: '/railway/group/',
    getParentRoute: () => Signed_inRoute,
  } as any)
const Signed_inRailwayGroupIdRoute = Signed_inRailwayGroupIdRouteImport.update({
  id: '/railway/group/$id',
  path: '/railway/group/$id',
  getParentRoute: () => Signed_inRoute,
} as any)
const Signed_inRailwayRailwayIndexRoute =
  Signed_inRailwayRailwayIndexRouteImport.update({
    id: '/railway/railway/',
    path: '/railway/railway/',
    getParentRoute: () => Signed_inRoute,
  } as any)
const Signed_inRailwayStationIndexRoute =
  Signed_inRailwayStationIndexRouteImport.update({
    id: '/railway/station/',
    path: '/railway/station/',
    getParentRoute: () => Signed_inRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof Signed_inIndexRoute
  '/plugins/lobby': typeof Signed_inPluginsLobbyRoute
  '/plugins/main': typeof Signed_inPluginsMainRoute
  '/plugins/res': typeof Signed_inPluginsResRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/auth/sign-in/': typeof AuthSignInIndexRoute
  '/railway/group/$id': typeof Signed_inRailwayGroupIdRoute
  '/railway/group/': typeof Signed_inRailwayGroupIndexRoute
  '/railway/railway/': typeof Signed_inRailwayRailwayIndexRoute
  '/railway/station/': typeof Signed_inRailwayStationIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof Signed_inIndexRoute
  '/plugins/lobby': typeof Signed_inPluginsLobbyRoute
  '/plugins/main': typeof Signed_inPluginsMainRoute
  '/plugins/res': typeof Signed_inPluginsResRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/auth/sign-in': typeof AuthSignInIndexRoute
  '/railway/group/$id': typeof Signed_inRailwayGroupIdRoute
  '/railway/group': typeof Signed_inRailwayGroupIndexRoute
  '/railway/railway': typeof Signed_inRailwayRailwayIndexRoute
  '/railway/station': typeof Signed_inRailwayStationIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_signed_in': typeof Signed_inRouteWithChildren
  '/_signed_in/': typeof Signed_inIndexRoute
  '/_signed_in/plugins/lobby': typeof Signed_inPluginsLobbyRoute
  '/_signed_in/plugins/main': typeof Signed_inPluginsMainRoute
  '/_signed_in/plugins/res': typeof Signed_inPluginsResRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/auth/sign-in/': typeof AuthSignInIndexRoute
  '/_signed_in/railway/group/$id': typeof Signed_inRailwayGroupIdRoute
  '/_signed_in/railway/group/': typeof Signed_inRailwayGroupIndexRoute
  '/_signed_in/railway/railway/': typeof Signed_inRailwayRailwayIndexRoute
  '/_signed_in/railway/station/': typeof Signed_inRailwayStationIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/plugins/lobby'
    | '/plugins/main'
    | '/plugins/res'
    | '/api/auth/$'
    | '/auth/sign-in/'
    | '/railway/group/$id'
    | '/railway/group/'
    | '/railway/railway/'
    | '/railway/station/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/plugins/lobby'
    | '/plugins/main'
    | '/plugins/res'
    | '/api/auth/$'
    | '/auth/sign-in'
    | '/railway/group/$id'
    | '/railway/group'
    | '/railway/railway'
    | '/railway/station'
  id:
    | '__root__'
    | '/_signed_in'
    | '/_signed_in/'
    | '/_signed_in/plugins/lobby'
    | '/_signed_in/plugins/main'
    | '/_signed_in/plugins/res'
    | '/api/auth/$'
    | '/auth/sign-in/'
    | '/_signed_in/railway/group/$id'
    | '/_signed_in/railway/group/'
    | '/_signed_in/railway/railway/'
    | '/_signed_in/railway/station/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  Signed_inRoute: typeof Signed_inRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  AuthSignInIndexRoute: typeof AuthSignInIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_signed_in': {
      id: '/_signed_in'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof Signed_inRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_signed_in/': {
      id: '/_signed_in/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof Signed_inIndexRouteImport
      parentRoute: typeof Signed_inRoute
    }
    '/_signed_in/plugins/lobby': {
      id: '/_signed_in/plugins/lobby'
      path: '/plugins/lobby'
      fullPath: '/plugins/lobby'
      preLoaderRoute: typeof Signed_inPluginsLobbyRouteImport
      parentRoute: typeof Signed_inRoute
    }
    '/_signed_in/plugins/main': {
      id: '/_signed_in/plugins/main'
      path: '/plugins/main'
      fullPath: '/plugins/main'
      preLoaderRoute: typeof Signed_inPluginsMainRouteImport
      parentRoute: typeof Signed_inRoute
    }
    '/_signed_in/plugins/res': {
      id: '/_signed_in/plugins/res'
      path: '/plugins/res'
      fullPath: '/plugins/res'
      preLoaderRoute: typeof Signed_inPluginsResRouteImport
      parentRoute: typeof Signed_inRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/sign-in/': {
      id: '/auth/sign-in/'
      path: '/auth/sign-in'
      fullPath: '/auth/sign-in/'
      preLoaderRoute: typeof AuthSignInIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_signed_in/railway/group/': {
      id: '/_signed_in/railway/group/'
      path: '/railway/group'
      fullPath: '/railway/group/'
      preLoaderRoute: typeof Signed_inRailwayGroupIndexRouteImport
      parentRoute: typeof Signed_inRoute
    }
    '/_signed_in/railway/group/$id': {
      id: '/_signed_in/railway/group/$id'
      path: '/railway/group/$id'
      fullPath: '/railway/group/$id'
      preLoaderRoute: typeof Signed_inRailwayGroupIdRouteImport
      parentRoute: typeof Signed_inRoute
    }
    '/_signed_in/railway/railway/': {
      id: '/_signed_in/railway/railway/'
      path: '/railway/railway'
      fullPath: '/railway/railway/'
      preLoaderRoute: typeof Signed_inRailwayRailwayIndexRouteImport
      parentRoute: typeof Signed_inRoute
    }
    '/_signed_in/railway/station/': {
      id: '/_signed_in/railway/station/'
      path: '/railway/station'
      fullPath: '/railway/station/'
      preLoaderRoute: typeof Signed_inRailwayStationIndexRouteImport
      parentRoute: typeof Signed_inRoute
    }
  }
}

interface Signed_inRouteChildren {
  Signed_inIndexRoute: typeof Signed_inIndexRoute
  Signed_inPluginsLobbyRoute: typeof Signed_inPluginsLobbyRoute
  Signed_inPluginsMainRoute: typeof Signed_inPluginsMainRoute
  Signed_inPluginsResRoute: typeof Signed_inPluginsResRoute
  Signed_inRailwayGroupIdRoute: typeof Signed_inRailwayGroupIdRoute
  Signed_inRailwayGroupIndexRoute: typeof Signed_inRailwayGroupIndexRoute
  Signed_inRailwayRailwayIndexRoute: typeof Signed_inRailwayRailwayIndexRoute
  Signed_inRailwayStationIndexRoute: typeof Signed_inRailwayStationIndexRoute
}

const Signed_inRouteChildren: Signed_inRouteChildren = {
  Signed_inIndexRoute: Signed_inIndexRoute,
  Signed_inPluginsLobbyRoute: Signed_inPluginsLobbyRoute,
  Signed_inPluginsMainRoute: Signed_inPluginsMainRoute,
  Signed_inPluginsResRoute: Signed_inPluginsResRoute,
  Signed_inRailwayGroupIdRoute: Signed_inRailwayGroupIdRoute,
  Signed_inRailwayGroupIndexRoute: Signed_inRailwayGroupIndexRoute,
  Signed_inRailwayRailwayIndexRoute: Signed_inRailwayRailwayIndexRoute,
  Signed_inRailwayStationIndexRoute: Signed_inRailwayStationIndexRoute,
}

const Signed_inRouteWithChildren = Signed_inRoute._addFileChildren(
  Signed_inRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  Signed_inRoute: Signed_inRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  AuthSignInIndexRoute: AuthSignInIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
