/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as Signed_inRouteImport } from './routes/_signed_in'
import { Route as Signed_inIndexRouteImport } from './routes/_signed_in/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AuthSignInIndexRouteImport } from './routes/auth/sign-in/index'

const Signed_inRoute = Signed_inRouteImport.update({
  id: '/_signed_in',
  getParentRoute: () => rootRouteImport,
} as any)
const Signed_inIndexRoute = Signed_inIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => Signed_inRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignInIndexRoute = AuthSignInIndexRouteImport.update({
  id: '/auth/sign-in/',
  path: '/auth/sign-in/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof Signed_inIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/auth/sign-in/': typeof AuthSignInIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof Signed_inIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/auth/sign-in': typeof AuthSignInIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_signed_in': typeof Signed_inRouteWithChildren
  '/_signed_in/': typeof Signed_inIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/auth/sign-in/': typeof AuthSignInIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/auth/$' | '/auth/sign-in/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/auth/$' | '/auth/sign-in'
  id:
    | '__root__'
    | '/_signed_in'
    | '/_signed_in/'
    | '/api/auth/$'
    | '/auth/sign-in/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  Signed_inRoute: typeof Signed_inRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  AuthSignInIndexRoute: typeof AuthSignInIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_signed_in': {
      id: '/_signed_in'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof Signed_inRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_signed_in/': {
      id: '/_signed_in/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof Signed_inIndexRouteImport
      parentRoute: typeof Signed_inRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/sign-in/': {
      id: '/auth/sign-in/'
      path: '/auth/sign-in'
      fullPath: '/auth/sign-in/'
      preLoaderRoute: typeof AuthSignInIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface Signed_inRouteChildren {
  Signed_inIndexRoute: typeof Signed_inIndexRoute
}

const Signed_inRouteChildren: Signed_inRouteChildren = {
  Signed_inIndexRoute: Signed_inIndexRoute,
}

const Signed_inRouteWithChildren = Signed_inRoute._addFileChildren(
  Signed_inRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  Signed_inRoute: Signed_inRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  AuthSignInIndexRoute: AuthSignInIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
